version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TIKTOK_CLIENT_ID=${TIKTOK_CLIENT_ID}
      - TIKTOK_CLIENT_SECRET=${TIKTOK_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
    volumes:
      - ./temp:/tmp
    restart: unless-stopped

  # Opcional: Redis para cache (se necessário)
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  # Opcional: PostgreSQL para produção (se necessário)
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: youtube_shorts
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:

